
server:
  port: 9090
spring:
  application:
    name: ApiGateWay-service  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  routes:
    orders:
      path: /order-service/**
      url: http://localhost:8083/
    users:
      path: /user-service/**
      url: http://localhost:8082/
    user-authentication:
      path: /user-authentication-service/**
      url: http://localhost:8081/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 20000      
    
  
