
server:
  port: 9090
spring:
  application:
    name: ApiGateWay-service  
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 20000      
    
  
