
server:
  port: 9090
spring:
  application:
    name: ApiGateWay-service  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
Not required if services are registered in Eureka
zuul:
  routes:
    orders:
      path: /order-service/**
      url: http://localhost:8083/
    users:
      path: /user-service/**
      url: http://localhost:8082/
    user-authentication:
      path: /user-authentication-service/**
      url: http://localhost:8081/
    
  
