
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/tire_management
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
logging:
  file: logs/application.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.cts.mc: INFO
    org.springframework: INFO
  
swagger:
   api-info:
       title: Order Service Api Documentation
       description: Order Test API Details
       version: v1.0
       termsOfServiceUrl: order
       contact:
          name: Order
          email: Uttam.Ghorai@cognizant.com
       license: Apache 2.0
       licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
      
