spring:
  application:
    name: user-authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/tire_management
    username: root
    password: 
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect  
server:
  port: 8081
  
swagger:
   api-info:
       title: Authentication Service Api Documentation
       description: Authentication Test API Details
       version: v1.0
       termsOfServiceUrl: order
       contact:
          name: Order
          email: Uttam.Ghorai@cognizant.com
       license: Apache 2.0
       licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
      
    
