spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/tire_management
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect  
server:
  port: 8082
  
swagger:
   api-info:
       title: User Service Api Documentation
       description: User Test API Details
       version: v1.0
       termsOfServiceUrl: order
       contact:
          name: User
          email: Uttam.Ghorai@cognizant.com
       license: Apache 2.0
       licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
      
  
